### ISSUE TITLE
[Calendar] Create calendar event view

### ISSUE THREAD

**Issue by tungnv2k** [tungnv2k/student_utils#2]
* Create base events visuals
* Make calendar events lazy loaded

**Comment by quanggnh** [comment]
Quick question: I just have to layout the view of the screen, do i have to make them interactable ?

**Comment by tungnv2k** [comment]
@quanghaopro You only have to build the view of CalendarScreen, the interactions are of UI animation issue. You may have to achieve either
* List view of Calendar Events
* Lazy loaded list view of Calendar Events (low latency)

**Comment by tungnv2k** [comment]
The UI also includes 

* A button to add events (bottom screen)
* A button to show menu
* A button to refresh calendar

These buttons are only views, where onPressed() {} function is empty

**Comment by tungnv2k** [comment]
* Replace calendar list with lazy loaded list, for low latency

**Comment by tungnv2k** [comment]
Further discussions at #49
