### ISSUE TITLE
[Calendar] Table calendar interact with scroll calendar

### ISSUE THREAD

**Issue by tungnv2k** [tungnv2k/student_utils#36]
* Use scroll controller jump to event from table calendar dates
* Change height for different table calendar views

**Comment by tungnv2k** [comment]
**Changing the organization of app bar and calendar list in Stack**
* The app bar will be on top
* The calendar list with table calendar will be in Wrap under app bar

**Comment by tungnv2k** [comment]
I'm using ScrollablePositionedList that is **not** working with your setState().

**Comment by quanggnh** [comment]
Sorry for late reply. I do that right away
